### ISSUE TITLE
Provide means for streaming and visualisation of semantic and hierarchical information of city objects using 3DTiles (N18)

### ISSUE THREAD

**Issue by jailln** [MEPP-team/UD-SV#21]
Refer to [Need018](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Needs/Need018.md)

**Comment by jailln** [comment]
(Design notes)[https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Design/DesignNote018.md]

**Comment by Jeremy-Gaillard** [comment]
Updated the design notes with a description of a first prototype and links to my contributions.

**Comment by EricBoix** [comment]
Humm, it looks like JGA started the job but didn't quite finish...

**Comment by EricBoix** [comment]
Done with Py3dTiles tilers.
Closed in weekly meeting
