### ISSUE TITLE
Realize a document visualization within a 3D representation of the city (N13)

### ISSUE THREAD

**Issue by EricBoix** [MEPP-team/UD-SV#4]
Realize [Need 13](https://github.com/MEPP-team/UD-SV/blob/master/UD-Doc/Needs/Need013.md)

**Comment by jailln** [comment]
There is a prototype for this need in : https://github.com/MEPP-team/UDV/tree/master/Vilo3D . This prototype uses a 2D screen overlay to display the documents as opposed to a 3D spatial insertion (as billboards for instance).

**Comment by sophiaab** [comment]
A first modelization has been proposed in the [DesignNote # 13](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Design/DesignNote013.md)

**Comment by EricBoix** [comment]
Closed in weekly.
